## 应用场景，此处布局排版为 6 快内容，如有数量变化，需要调整布局：css/_partial/album.styl
# name:         标题
# en_name:      英文标题
# description:  描述内容
# cover:        封面图片路径
# link:         链接路径，无链接为空即可
# preview:      预览路径，无则可以为空
#
- name: 车辆动态管理
  en_name: VEHICLE DYNAMIC MANAGEMENT
  description: 提供规划、设计、建设为一体的车辆出入场景服务方案，车牌高清动态管理、车位引导、支持第三方支付接入、提供对外标准接口，打造智慧化车辆管控系统。
  cover: /products/screenshots/scenario_cars.jpg
  link: 
  preview: 

- name: 智能门锁应用
  en_name: SMART DOOR LOCK APPLCATION
  description: 解决主动性的安全问题，异常报警、C 级锁芯防护，具备刷卡、密码、指纹等多重验证；提供蓝牙/433/ ZIGBEE 主流通讯方式，支持 APP 开门及客户化定制；提供智能化数据联动，可集成一卡通统一刷卡，智慧公寓宿舍调配联动，进出房间数据实施统计等。
  cover: /products/screenshots/scenario_lock.jpg
  link: 
  preview: 

- name: 通道智能识别
  en_name: CHANNEL INTELLIGENT RECOGNITION
  description: 引领潮流的外观设计，高效精准的机械控制，客户化元素的定制为理念，支持 AI 识别、C 卡、NFC、二维码等多种方式通行。
  cover: /products/screenshots/scenario_gate.jpg
  link: 
  preview: 

- name: 门禁高效管理
  en_name: EFFICIENT ACCESS CONTROL MANAGEMENT
  description: 以太网联网，主动上传数据；单门双向、两门双向、四门单向可选支持韦根或 RS485 读卡器；支持10万用户/10万脱机事件记录；支持外接4输入/4继电器输出扩展版。
  cover: /products/screenshots/scenario_access.jpg
  link: 
  preview: 

- name: AI 应用终端
  en_name: AI APPLICATION TERMINAL
  description: 圣思睿场景应用智慧管理平台秉承“大平台+模块化”概念，以场景智慧化建设为整体框架，以平台+模块化技术为牵引，完成出入口、楼宇、房间的统一化管理与数据智能分析。
  cover: /products/screenshots/scenario_ai.jpg
  link: 
  preview: 

- name: 智慧公寓管理
  en_name: SMART APARTMENT MANAGEMENT
  description: 智慧公寓主要应用于校园学生管理，支持接入通道管理、门禁管理、智能门锁，通过数据 AI 分析，为公寓提供安全、便捷、高效的信息化管理，也为领导层提供全方位的省心管家服务。
  cover: /products/screenshots/scenario_apartment.jpg
  link: 
  preview: 
